### PR TITLE
fix: force checktime to autoread package.json

### LINKED ISSUE #120: Bug trying to edit a `package.json` with unsaved changes
`E5108: Error executing lua .../opt/package-info.nvim/lua/package-info/modules/core.lua:173: Vim(edit):E37
: No write since last change (add ! to override)`

You can't run `:e` on an file with unsaved changes

https://github.com/vuki656/package-info.nvim/blob/10de4d0d50ec1d4d26118c4aa067a9d09e370c9c/lua/package-info/modules/core.lua#L171-L175

### PR DESCRIPTION
**Pull request by pedro757**
fixes #120

### CODE REVIEW

**Comment by vuki656** [comment]
Thanks for the PR.

Can you please explain how this works? I'm not familiar with the `checktime` and `autoread`.

**Comment by pedro757** [comment]
Vim works doesn't edit the file directly instead it creates a buffer which may be equal or not to the file. If you set `autoread` it will be looking for changes in the file to apply within the buffer, however I think it has some delay or something because I always have `autoread` set but it doesn't detects the changes immediately, that's why we use `:checktime` to force a check, so it can detect changes in the file and then apply them in the buffer.

**Comment by vuki656** [comment]
Just read up a little on these two options and I think I get what they do but I'm not sure what is the benefit of your solution over the current one.

Can you explain a bit how it would be more beneficial than the current implementation?

**Comment by vuki656** [comment]
Also, I've merged a major refactor that has been sitting for a long time. So it might be easier to make the change from the master again if the conflicts are nasty.

**Comment by pedro757** [comment]
If you try to do this with views you will come across these issues because it is not a good approach

image

Look at what happened to the versions, it duplicates the virtual text, it is better just to force a `:checktime`.

Apparently in next versions of neovim like 0.9+ it will have better file-change detection. https://neovim.io/roadmap/

**Comment by vuki656** [comment]
> If you try to do this with views you will come across these issues because it is not a good approach
> 
> image
> 
> Look at what happened to the versions, it duplicates the virtual text, it is better just to force a `:checktime`.
> 
> Apparently in next versions of neovim like 0.9+ it will have better file-change detection. https://neovim.io/roadmap/

Alrighty, can you just resolve the conflicts and I'll merge.

**Pull request closed without merging**
