### PR TITLE
feat: support yarn 1

### LINKED ISSUE #104: Support for Yarn 1.x.x
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'm aware that this was recently removed, as well as the personal opinions regarding Yarn 2 usage, but I personally don't have a lot of choice for work projects which version of Yarn I can use. Might there still be a way to support "legacy" projects that require Yarn 1?

Thanks for the consideration.

### Help

No, sorry.

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by vuki656**
Not the cleanest solution but I plan to rewrite a lot of stuff in the plugin soon so that should take care of it. 

Closes #104

### CODE REVIEW

**Comment by Iamafnan** [comment]
Hey @vuki656 how can I use this pr instead of the main branch?

**Comment by vuki656** [comment]
> Hey @vuki656 how can I use this pr instead of the main branch?

You just need to specify the branch, like so 

```lua
use({
    "vuki656/package-info.nvim",
    branch = "feat/yarn-1-support",
    requires = { "muniftanjim/nui.nvim" },
})
```

**Comment by Iamafnan** [comment]
Thanks
I have tested yarn 1 branch and it is working fine for me all the functions are working good

**Comment by vuki656** [comment]
> Thanks I have tested yarn 1 branch and it is working fine for me all the functions are working good

Thanks for testing it.

**Pull request merged**
