### PR TITLE
Add Telescope extension

### PR DESCRIPTION
**Pull request by Ty3uK**
Don't know what to say 🙈

Just simple picker for Telescope, I found it useful in my workflow 🙂

https://user-images.githubusercontent.com/2384454/226606753-e50bcced-04eb-45dc-ab7a-dd306d229d5e.mp4

### CODE REVIEW

**Comment by Ty3uK** [comment]
@vuki656, dunno what to do with two failed actions 🥲

**Comment by vuki656** [comment]
Hey, thanks for the PR. Will review in the next few days.

As for the pipeline failing, I assume it's because of the outdated versions of nvim or GitHub actions. If you have the time look into it.

I would like to raise the minimum nvim version to 7 and update GitHub actions to the latest version.

**Comment by Ty3uK** [comment]
> As for the pipeline failing, I assume it's because of the outdated versions of nvim or GitHub actions. If you have the time look into it.

@vuki656, done, waiting for your check (no rush) 🙂

**Comment by vuki656** [comment]
Thanks for the PR <3

**Pull request merged**
