### PR TITLE
Fix buffer error when swtiching from one package.json to another

### LINKED ISSUE #74: [BUG] line value outside range and virtual text being duplicated (probably due to yarn workspaces)
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.5 neovim version

### Neovim Version

v0.6.0-dev+235-ga422f2136

### Branch

master

### Actual behavior

I am using [yarn workspaces](https://yarnpkg.com/features/workspaces#workspace-ranges-workspace) and have multiple `package.json` open at the same time.

I don't know exactly when this happens, but after a while when I have opened a `package.json` that uses another workspace, I get errors when opening `package.json`s:
```
E5108: Error executing lua ...tart/package-info.nvim/lua/package-info/modules/core.lua:183: line value outside range
```
and the virtual text that contains package versions is often duplicated:

The right `package.json` does not contain any `workspace:*` packages.

### Expected behavior

The versions are shown only once and there are no errors in `:messages`

### Steps to reproduce

Part of one `package.json`:

```json
{
  "dependencies": {
    "@cloud/unified": "workspace:*",
    "@graphile-contrib/pg-simplify-inflector": "6.1.0",
    "fastify": "3.14.2",
    "graphile-build": "4.11.0",
    "graphile-build-pg": "4.11.2",
    "graphile-utils": "4.11.2",
    "graphql": "14.7.0",
    "graphql-config": "3.2.0",
    "pg": "8.5.1",
    "pg-native": "3.0.0",
    "postgraphile": "4.11.0"
  },
  "devDependencies": {
    "@types/pg": "7.14.11",
    "nodemon": "2.0.12",
    "npm-run-all": "4.1.5"
  }
```

Part of another `package.json`:
```json
{
  "dependencies": {
    "fastify": "3.14.2",
    "fastify-cookie": "5.3.0",
    "isomorphic-unfetch": "3.1.0",
    "pg": "8.5.1",
    "pg-native": "3.0.0",
    "wkx": "0.5.0"
  },
  "devDependencies": {
    "ts-node": "9.1.1"
  }
}
```

Open both of them side by side. Run `:e` multiple times on the 2nd `package.json`.

### Package info config

The `setup` config is empty:
https://github.com/Gelio/ubuntu-dotfiles/blob/89861fb0ee589337a7343dbb759b88f3b0772b96/install/neovim/stowed/.config/nvim/lua/plugins.lua#L532

### Other information

_No response_

### Help

No, sorry.

### Implementation help

_No response_

### PR DESCRIPTION
**Pull request by jwickers**
Signed-off-by: Jeremy Wickersheimer <jwickers@gmail.com>

This should fix #74

### CODE REVIEW

**Comment by vuki656** [comment]
Hey, thanks for the PR. Would you mind opening this to the `[ref/reorganize-code](https://github.com/vuki656/package-info.nvim/tree/ref/reorganize-code)` branch? 

I've rewritten the plugin but never got around to merging it to master.

**Comment by jwickers** [comment]
It's only one line of code, feel free to copy it or cherry-pick it there if that still works. I would have to test it in that branch. 

Is it still WIP though ? else why not make it master at this point?

**Comment by vuki656** [comment]
I finished it and then was testing it but never got around to merging it.

I'll merge it this weekend and include your fix in it.

**Comment by jwickers** [comment]
Nice. Well I update pretty regularly and use your plugin daily as well, so I'll have a look after the merge.

**Comment by vuki656** [comment]
Added in https://github.com/vuki656/package-info.nvim/commit/be3a76dd39f6725e419b46e5946bb2a60522f157

**Pull request closed without merging**
